### ISSUE TITLE
低解像度(1334x750)のJpeg認識でnot valid になる

### ISSUE THREAD

**Issue by amenohimo** [fgophi/fgosccnt#116]
```
IMG_7115.jpg: not valid,,12,,,,,,,,,,,,,,,
IMG_7120.jpg: not valid,,11,,,,,,,,,,,,,,,
IMG_7122.jpg: not valid,,12,,,,,,,,,,,,,,,
```

![IMG_7115](https://user-images.githubusercontent.com/6458565/87507305-26718280-c6a8-11ea-94fc-73f8e4dcd9e4.jpg)
![IMG_7120](https://user-images.githubusercontent.com/6458565/87507313-283b4600-c6a8-11ea-8cbe-4154bd1bc2b2.jpg)
![IMG_7122](https://user-images.githubusercontent.com/6458565/87507317-2a050980-c6a8-11ea-99b8-3277ba6e9b86.jpg)

**Comment by fgophi** [comment]
fgosccnt をクリーンインストールした結果不具合は確認できませんでした

次の原因が考えられます
- 最新版にしていない
- makeitem.py makecard.py を再実行していない

```
$ python fgosccnt.py *.jpg
filename,ドロ数,QP(+9400),卵,貝殻,鎖,槍秘,槍輝,槍猛火,QP(+1百万)
合計,,3,3,1,8,1,1,20,1
IMG_7115.jpg,12,1,1,1,1,,1,7,1
IMG_7120.jpg,11,1,1,,4,,,6,
IMG_7122.jpg,12,1,1,,3,1,,7,
```
