### ISSUE TITLE
低解像度(1334x750)のJpeg認識でnot validになる

### ISSUE THREAD

**Issue by amenohimo** [fgophi/fgosccnt#118]
```
$python fgosccnt.py IMG_7124.jpg IMG_7128.jpg"
filename,ドロ数
合計,
IMG_7124.jpg: not valid,
IMG_7128.jpg: not valid,
```
2/19 (10.5%)

![IMG_7128](https://user-images.githubusercontent.com/6458565/87510717-0b564100-c6af-11ea-8568-9d42a2039052.jpg)
![IMG_7124](https://user-images.githubusercontent.com/6458565/87510713-098c7d80-c6af-11ea-994f-3bd1e521ef92.jpg)

**Comment by fgophi** [comment]
not valid 確認できませんでした
```
$ python fgosccnt.py IMG_7124.jpg IMG_7128.jpg
filename,ドロ数,QP(+9400),鎖,槍秘,槍魔,槍大火,槍猛火
合計,,2,4,1,2,2,19
IMG_7124.jpg,14,1,2,,1,1,10
IMG_7128.jpg,14,1,2,1,1,1,9
```

**Comment by amenohimo** [comment]
fix #117 を適用後、こちらでも認識できました

**Comment by amenohimo** [comment]
IMG_7124.jpg, IMG_7128 の画像ですが、
not valid はでなくなりましたが、猛火が1つずつ少ないです
それぞれ11個、10個ですが、10個、9個になっています

**Comment by amenohimo** [comment]
```
filename,ドロ数
合計,
IMG_6697.PNG: not valid,
IMG_6878.jpg: not valid,
```
![IMG_6697](https://user-images.githubusercontent.com/6458565/87525814-f8e70200-c6c4-11ea-8080-6bf6f197b1c7.PNG)
![IMG_6878](https://user-images.githubusercontent.com/6458565/87525838-00a6a680-c6c5-11ea-94ef-2cc44ddb41d4.jpg)

**Comment by fgophi** [comment]
> IMG_7124.jpg, IMG_7128 の画像ですが、
> not valid はでなくなりましたが、猛火が1つずつ少ないです
> それぞれ11個、10個ですが、10個、9個になっています

1つ槍大火と誤認識
```
$ fgosccnt IMG_7124.jpg  IMG_7128.jpg
filename,ドロ数,QP(+9400),鎖,槍秘,槍魔,槍大火,槍猛火
合計,,2,4,1,2,2,19
IMG_7124.jpg,14,1,2,,1,1,10
IMG_7128.jpg,14,1,2,1,1,1,9
```

**Comment by fgophi** [comment]
種火に関しては3行目にくることを想定していなかったので、種火のレアリティを判定するルーチンを通ってない
そのため、間違えたレアリティで判定されている
通常ならば Card Type: Exp. UP となる

```
[Item14 Information]
Card Type:
Name: 槍大火
```
